apiVersion: apps/v1
kind: Deployment
metadata:
  name: datamodel
  labels:
    app: datamodel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datamodel
  template:
    metadata:
      labels:
        app: datamodel
    spec:
      containers:
      - name: datamodel
        image: gcr.io/broad-dsp-devops-k8s/terrainteropmodel:0.0.36
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: datamodel-tls-secret
          mountPath: "/etc/datamodel/ssl"
          readOnly: true
      volumes:
      - name: datamodel-tls-secret
        secret:
          secretName: datamodel-tls-secret