apiVersion: v1
kind: Service
metadata:
  name: datamodel
spec:
  selector:
    app: datamodel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalIPs: 
    - 104.196.71.219
  type: LoadBalancer